---
abstract: 'Basic framework to provide DTD catalogs'
author:
  - 'Eric Brine, C<< <ikegami@adaelis.com> >>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Catalogs
provides:
  XML::Catalogs:
    file: lib/XML/Catalogs.pm
    version: v1.4.0
requires:
  Carp: '0'
  File::ShareDir: '0'
  URI::file: '0'
  version: '0'
version: v1.4.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
